name = froscon
fosdem_password = hi-from-st-augustin!

# Other settings, tweak as needed
enable_esc_dialog = false
font_size = 16
gui_scaling = 1.2
enable_damage = true
creative_mode = true
menu_last_game = cow
server_announce = false
screen_h = 1011
screen_w = 1920
window_maximized = true
maintab_LAST = content
